<a href="https://colab.research.google.com/github/Harmangill30/Big-Data/blob/main/Assignment2_31jan2024_202301021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3,6,4,5])
print(np.flip(a))



[5 4 6 3 2 1]


In [ ]:
b=np.array([[1,2],[3,4]])
c=np.array([[1,2],[3,4]])
print(b==c)


[[ True  True]
 [ True  True]]


In [13]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1, 2, 3, 4, 2, 4, 3, 3])
print(f"The most frequent value in  first array is : {np.bincount(x).argmax()}")
print(f"The index of most frequent values of first array are {np.where(x==(np.bincount(x).argmax()))}")
print(f"The most frequent value in  second array is : {np.bincount(y).argmax()}")
print(f"The index of most frequent values of second array are {np.where(y==(np.bincount(y).argmax()))}")

the most frequent value in  first array is : 1
the index of most frequent values of first array are (array([0, 5, 7, 8, 9]),)
the most frequent value in  second array is : 1
the index of most frequent values of second array are (array([0, 1, 2]),)


In [9]:
x = np.matrix("[4, 1, 9; 12, 3, 1; 4, 5, 6]")
print(x)
print(f"The sum of matrix is {np.sum(x)}")
print(f"The sum of all rows are {x.sum(axis=1)}")
print(f"The sum of all columns  are {x.sum(axis=0)}")

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
The sum of matrix is 45
The sum of all rows are [[14]
 [16]
 [15]]
The sum of all columns  are [[20  9 16]]
